In [30]:
import matplotlib.pyplot as plt
from scipy import stats
import numpy as np
import pandas as pd
from pylab import *
from scipy import *

city_data = pd.read_csv("Pyber/raw_data/city_data.csv")
ride_data = pd.read_csv("Pyber/raw_data/ride_data.csv")

In [31]:
ride_data.groupby(['city','fare']).mean()

                           ride_id
city           fare
Alvarezhaven   4.07   6.100187e+12
               5.16   2.233026e+12
               5.34   1.108172e+12
               6.42   8.394540e+12
               6.45   8.939752e+12
               6.72   6.152999e+12
               9.87   2.747592e+12
               14.25  6.431434e+12
               17.67  3.829337e+12
               18.09  1.197330e+12
               20.23  4.348900e+12
               20.61  8.307812e+12
               20.74  3.574212e+11
               20.88  9.456788e+12
               22.54  6.435260e+12
               22.83  3.565582e+12
               24.16  9.047320e+12
               27.51  6.282666e+12
               31.08  7.413831e+12
               31.74  5.487021e+12
               31.82  7.948247e+12
               31.93  4.267016e+12
               32.46  8.586315e+11
               33.31  3.060544e+11
               33.62  8.974645e+12
               35.22  5.405757e+12
               39.28  8.878746e+12
               40.04  1.806813e+12
               42.00  7.852568e+12
               42.41  7.825539e+12
...                            ...
Yolandafurt    34.95  9.030132e+12
               35.75  1.266756e+12
               36.00  6.313980e+12
               36.08  9.895622e+12
               41.96  9.633878e+11
               43.36  6.404298e+11
Zimmermanmouth 5.27   8.859329e+11
               5.97   7.276044e+12
               14.36  7.886293e+12
               14.50  7.547395e+12
               16.21  4.966546e+12
               17.12  1.214604e+12
               20.96  6.490498e+12
               21.88  1.942308e+12
               24.23  3.364399e+12
               24.69  9.508846e+12
               26.23  6.060050e+12
               26.63  2.326214e+12
               28.89  1.529364e+12
               34.65  3.806179e+12
               34.84  7.176327e+12
               34.95  2.258161e+12
               37.04  9.089070e+12
               39.65  5.690109e+12
               40.95  5.672694e+12
               41.16  3.880962e+11
               41.58  7.488861e+12
               41.96  5.202604e+12
               42.01  5.892577e+11
               43.51  2.489773e+12

[2371 rows x 1 columns]

In [35]:
#Total number of rides per city

Ride_totals=ride_data['ride_id'].count()
ride_data['ride_id'].count()

2375

In [36]:
Ride_totals= len(ride_data['city'].unique())
ride_data['ride_id'].unique()

array([5403689035038, 4036272335942, 3645042422587, ..., 4165974278063,
       4336212615821, 5702608059064], dtype=int64)

In [38]:
Ride_totals=ride_data['city'].value_counts()['ride_id']
ride_data['ride_id'].value_counts()

KeyError: 'ride_id'